/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct MyStruct {
	int field1;
	int field2;
};
typedef struct MyStruct MyStruct;

#define MYPROG 0x20000013
#define MYVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define P1 1
extern  int * p1_1(MyStruct *, CLIENT *);
extern  int * p1_1_svc(MyStruct *, struct svc_req *);
#define P2 2
extern  int * p2_1(MyStruct *, CLIENT *);
extern  int * p2_1_svc(MyStruct *, struct svc_req *);
extern int myprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define P1 1
extern  int * p1_1();
extern  int * p1_1_svc();
#define P2 2
extern  int * p2_1();
extern  int * p2_1_svc();
extern int myprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_MyStruct (XDR *, MyStruct*);

#else /* K&R C */
extern bool_t xdr_MyStruct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
